/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  usuario
 * Created: 22-abr-2019
 */
CREATE TABLE FABRICANTE (
    ID_FABRICANTE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    FECHA_CREACION DATE,
    FOTO VARCHAR(500),
    HISTORIA VARCHAR(500),
    CONSTRAINT ID_FABRICANTE_FABRICANTE_PK PRIMARY KEY (ID_FABRICANTE)
);

CREATE TABLE GUITARRA (
    ID_GUITARRA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    FABRICANTE INTEGER,
    AÑO DATE,
    MODELO VARCHAR(100) NOT NULL,
    FOTO VARCHAR(500),
    STOCK BOOLEAN,
    PRECIO DECIMAL(7,2),
    MADERA VARCHAR(100),
    TIPO VARCHAR(100),
    CONSTRAINT ID_GUITARRA_GUITARRA_PK PRIMARY KEY (ID_GUITARRA),
    CONSTRAINT FABRICANTE_ID_FRABRICANTE_FK FOREIGN KEY (FABRICANTE) REFERENCES FABRICANTE (ID_FABRICANTE)
);


